import json
import smtplib
import threading
from dataclasses import dataclass
from email.message import EmailMessage
from pathlib import Path
from typing import List, Optional


CONFIG_PATH = Path(__file__).with_name("config.json")


@dataclass
class EmailConfig:
    """Email profile: one sender with one or more recipients.

    Multiple profiles can be configured in config.json under "email_profiles".
    """

    name: str
    smtp_server: str
    smtp_port: int
    use_tls: bool
    sender_email: str
    sender_password: str
    recipients: List[str]

    @staticmethod
    def from_dict(d: dict) -> "EmailConfig":
        recipients = d.get("recipients")
        if recipients is None:
            # Backwards compatibility: single "recipient_email" field
            single = d.get("recipient_email")
            recipients = [single] if single else []
        return EmailConfig(
            name=d.get("name", d.get("sender_email", "default")),
            smtp_server=d["smtp_server"],
            smtp_port=int(d["smtp_port"]),
            use_tls=bool(d.get("use_tls", True)),
            sender_email=d["sender_email"],
            sender_password=d["sender_password"],
            recipients=list(recipients),
        )


def load_email_profiles() -> List[EmailConfig]:
    """Load all configured email profiles.

    Supports two config formats:
    - New:  "email_profiles": [ { ... }, { ... } ]
    - Legacy: "email": { ... }
    """
    if not CONFIG_PATH.exists():
        return []
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    profiles_data = []
    if "email_profiles" in data:
        profiles_data = data["email_profiles"]
    elif "email" in data:
        profiles_data = [data["email"]]

    return [EmailConfig.from_dict(d) for d in profiles_data]


def load_email_config() -> Optional[EmailConfig]:
    """Return the first configured email profile (for backwards compatibility)."""
    profiles = load_email_profiles()
    return profiles[0] if profiles else None


def _send_key_email_sync(config: EmailConfig, password: str) -> None:
    msg = EmailMessage()
    msg["Subject"] = "New Encryption Key (Time-based Rotation)"
    msg["From"] = config.sender_email
    msg["To"] = ", ".join(config.recipients)

    body = (
        "A new encryption password has been generated by the Advanced File Protection System.\n\n"
        f"Password: {password}\n"
        "Note: Treat this password as sensitive information. Do not share it with unauthorized users."
    )
    msg.set_content(body)

    try:
        if config.use_tls:
            with smtplib.SMTP(config.smtp_server, config.smtp_port) as server:
                server.starttls()
                server.login(config.sender_email, config.sender_password)
                server.send_message(msg)
        else:
            with smtplib.SMTP(config.smtp_server, config.smtp_port) as server:
                server.login(config.sender_email, config.sender_password)
                server.send_message(msg)
    except smtplib.SMTPAuthenticationError as e:
        # Authentication failure (e.g., wrong password or provider blocking login)
        print(f"[Email:{config.name}] Authentication failed while sending key email:", e)
    except Exception as e:
        # Any other email-related error
        print(f"[Email:{config.name}] Failed to send key email:", e)


def send_key_email_async(config: EmailConfig, password: str) -> None:
    """Send the key email in a background thread so that the GUI does not block."""

    thread = threading.Thread(
        target=_send_key_email_sync,
        args=(config, password),
        daemon=True,
    )
    thread.start()


def send_key_email_to_all(configs: List[EmailConfig], password: str) -> None:
    """Send the key email through all configured email profiles using their default recipients."""
    for cfg in configs:
        send_key_email_async(cfg, password)


def send_key_email_to_recipients(configs: List[EmailConfig], recipients: List[str], password: str) -> None:
    """Send the key email to a specific list of recipients via all configured senders."""
    for cfg in configs:
        override = EmailConfig(
            name=cfg.name,
            smtp_server=cfg.smtp_server,
            smtp_port=cfg.smtp_port,
            use_tls=cfg.use_tls,
            sender_email=cfg.sender_email,
            sender_password=cfg.sender_password,
            recipients=list(recipients),
        )
        send_key_email_async(override, password)


def send_key_email_with_override(
    template: EmailConfig,
    sender_email: str,
    sender_password: str,
    recipients: List[str],
    password: str,
) -> None:
    """Send key email using a runtime sender + recipients, based on an SMTP template profile."""
    override = EmailConfig(
        name=template.name,
        smtp_server=template.smtp_server,
        smtp_port=template.smtp_port,
        use_tls=template.use_tls,
        sender_email=sender_email,
        sender_password=sender_password,
        recipients=list(recipients),
    )
    send_key_email_async(override, password)
